site_name: Ingresso.EEAR

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Ingresso.eear

theme:
        name: material
        language: pt

nav:
        - Home: index.md
        - Planejamento: planejamento.md
        - Apresentações: apresentacoes.md

