site_name: Ingresso.EEAR

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Ingresso.eear

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt
        logo: assets/imagens/logo_eear.png
        favicon: assets/imagens/favicon.ico

nav:
        - Home: index.md
        - Planejamento: planejamento.md
        - Análise de Requisitos:
                - Perfil do Usuário: analise-de-requisitos/perfil-do-usuario.md
                - Personas: analise-de-requisitos/personas.md
                - Análise de Tarefas: analise-de-requisitos/analise-de-tarefas.md
                - Metas de Usabilidade: analise-de-requisitos/metas-de-usabilidade.md
                - Princípios Gerais do Projeto: analise-de-requisitos/principios-gerais.md
                - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
        - Design, avaliação e desenvolvimento:
                - Nível 1:
                        - Storyboard: design-ava-dese/nivel-1/storyboard.md
                        - Avaliações: 
                                - Planejamento e Avaliação do Storyboard: design-ava-dese/nivel-1/avaliacoes/plan-ava-storyboard.md
                                - Planejamento e Avaliação da Análise de Tarefas: design-ava-dese/nivel-1/avaliacoes/plan-ava-ana-tarefas.md
                - Nível 2:
                        - Relato dos Resultados do Storyboard: design-ava-dese/nivel-1/avaliacoes/resultado-ava-storyboard.md
                        - Planejamento da Protótipo de Papel: design-ava-dese/nivel-2/plan-prototipo-papel.md
        - Apresentações: apresentacoes.md
        - Atas:
                - 23/02/2021: atas/reuniao-23-02-2021.md
                - 13/03/2021: atas/reuniao-13-03-2021.md
                - 20/03/2021: atas/reuniao-20-03-2021.md
                - 01/04/2021: atas/reuniao-01-04-2021.md
