site_name: Ingresso.EEAR

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Ingresso.eear

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt
        logo: assets/imagens/logo_eear.png
        favicon: assets/imagens/favicon.ico

nav:
        - Home: index.md
        - Planejamento: planejamento.md
        - Análise de Requisitos:
                - Perfil do Usuário: analise-de-requisitos/perfil-do-usuario.md
                - Personas: analise-de-requisitos/personas.md
                - Análise de Tarefas: analise-de-requisitos/analise-de-tarefas.md
                - Metas de Usabilidade: analise-de-requisitos/metas-de-usabilidade.md
                - Princípios Gerais do Projeto: analise-de-requisitos/principios-gerais.md
                - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
        - Design, avaliação e desenvolvimento:
                - Nível 1:
                        - Análise de Tarefas:
                                - Planejamento e Avaliação da Análise de Tarefas: design-ava-dese/nivel-1/ana-tarefas/plan-ava-ana-tarefas.md
                                - Relato dos Resultados da Avaliação da Análise de Tarefas:
                                        - Avaliação da Tarefa 1: design-ava-dese/nivel-1/ana-tarefas/resultados/avaliacao-efetua.md
                                        - Avaliação da Tarefa 2: design-ava-dese/nivel-1/ana-tarefas/resultados/avaliacao-acompanha.md
                        - Storyboards: 
                                - Storyboards: design-ava-dese/nivel-1/storyboards/storyboards.md
                                - Planejamento da Avaliação do Storyboard: design-ava-dese/nivel-1/storyboards/plan-ava-storyboard.md
                                - Relato dos Resultados da Avaliação do Storyboard: design-ava-dese/nivel-1/storyboards/resultado-ava-storyboard.md
                - Nível 2:
                        - Planejamento do Protótipo de Baixa Fidelidade: design-ava-dese/nivel-2/plan-prototipo-papel.md
                        - Relato dos Resultados da Avaliação do Protótipo de Baixa Fidelidade: design-ava-dese/nivel-2/resultado-prot-papel.md
                - Nível 3:
                        - Planejamento do Protótipo de Alta Fidelidade: design-ava-dese/nivel-3/plan-prototipo-alta.md
                        - Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: design-ava-dese/nivel-3/resultado-prot-alta.md
        - Análise:
                - Verificação:
                        - Personas: analise/verificacao/personas.md
                        - Storyboards: analise/verificacao/storyboards.md
                        - Relato dos Resultados da Avaliação do Storyboard: analise/verificacao/resultado-ava-storyboard.md
        - Apresentações: apresentacoes.md
        - Atas:
                - 23/02/2021: atas/reuniao-23-02-2021.md
                - 13/03/2021: atas/reuniao-13-03-2021.md
                - 20/03/2021: atas/reuniao-20-03-2021.md
                - 01/04/2021: atas/reuniao-01-04-2021.md
                - 15/04/2021: atas/reuniao-15-04-2021.md
                - 26/04/2021: atas/reuniao-26-04-2021.md
